var KEY_STORAGE_SETTINGS = "settings"
    , DEFAULT_AUTO_DOWNLOAD = false
    , DEFAULT_PICTURE_FORMAT = "png"
    , DEFAULT_VIDEO_WIDTH = 800
    , DEFAULT_VIDEO_HEIGHT = 600
    , DEFAULT_ASPECT_RATIO = false
    , DEFAULT_GIF_QUALITY = 50
    , DEFAULT_JPEG_QUALITY = 75
;
